# Generated by Django 4.1.5 on 2023-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_userprofile_qrcode_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vcard',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(default='', max_length=256),
        ),
    ]
